### ISSUE TITLE
Dismiss does not work when using .loading alert

### ISSUE THREAD

**Issue by bzbislawski** [elai950/AlertToast#16]
**Describe the bug**
I expect to display loading alert. Once Published variable changes to different value then I'd expect new alert to display only 2 seconds, not infinite. Also tap to dismiss does not work in this case

**Expected behavior**
`.toast(isPresenting: $showToast) {
            if viewModel.sendMessageResponse == .successfullySent {
                return AlertToast(type: .complete(.green), title: "Message Sent!", custom: .custom(backgroundColor: Color.customYellow))
            } else if viewModel.sendMessageResponse == .errornousResponse {
                return AlertToast(type: .error(.red), title: "Unable to send message!", custom: .custom(backgroundColor: Color.customYellow))
            }  else {
                return AlertToast(displayMode: .alert, type: .loading, custom: .custom(backgroundColor: Color.customYellow))
            }`

Steps
1. Change showToast to true -> this displays loading alert
2. Waiting for async call to update sendMessageResponse to .successfullySent or .errornousResponse
3. Alert green or red is displayed infinitely and it is impossible to to tap to dismiss success/error alert.

**Comment by elai950** [comment]
You should create an `@Published var alertToast: AlertToast` object in `ObservableObject` instead of using `if else`.

[Read the bonus section here](https://medium.com/swlh/presenting-apples-music-alerts-in-swiftui-7f5c32cebed6)

Then just add functions to set the `alertToast` var.

```swift
class AlertViewModel: ObservableObject{
    
    /// ... properties

  func showComplete(){
     alertToast = AlertToast(type: .complete(.green), title: "Message Sent!", custom: .custom(backgroundColor: Color.customYellow))
  }

}
```

When your async call update (for example) the sendMessageResponse just set call `showComplete()` func.

Also,
The loading alert toast disables the tapToDismiss and sets the duration to 0 for his view modifier, so I recommend creating 2 different `.toast` view modifiers (you can add multiple toast view modifiers on the same view).
One for the loading and another one for Complete & Error.

**Comment by bzbislawski** [comment]
```
One for the loading and another one for Complete & Error.
```
Yes, this is what I did.
I also hoped that maybe completion modifier can return another alert but it is not a case. Thanks

**Comment by elai950** [comment]
Just add 'showComplete/Error.toggle()' in the completion handler.
