### ISSUE TITLE
displayMode messes up my screens navigation

### ISSUE THREAD

**Issue by SomebodyInTheWorld1** [elai950/AlertToast#34]
Here is the video of my problem. It's pretty simple. I realized that when I use `displayMode: .alert` everything works fine, but with any other displayMode it messes up navigation and navigation doesn't work properly. It's like it reopens the same screen and just displays toast.

I cannot figure out why. If you need further explanation I can give it to you :)

Video: https://vimeo.com/663400646

**Comment by jthorel** [comment]
Old issue yes but I had the same problem. Weird navigation issues with using an environmentObject.

And I just now fixed it actually.

I had to explicitly set .navigationStyle(.stack) on the NavigationView (as I see you have not as well) or else the navigation would bug out. So the issue is something SwiftUI related, not AlertToast.

**Comment by elai950** [comment]
> Old issue yes but I had the same problem. Weird navigation issues with using an environmentObject.
> 
> And I just now fixed it actually.
> 
> I had to explicitly set .navigationViewStyle(.stack) on the NavigationView (as I see you have not as well) or else the navigation would bug out. So the issue is something SwiftUI related, not AlertToast.

Also @SomebodyInTheWorld1 ,
Please try to move your toast modifier from the `NavigationView` and put it on any other children's view.
