### ISSUE TITLE
Toaster not clearing on first call

### ISSUE THREAD

**Issue by pulpfree** [elai950/AlertToast#38]
**Description**
When the initial call to AlertToast is made, it does not clear after the default 2 seconds.  Subsequent calls to AlertToast do properly clear after the duration.

This is only a problem when using the `.hud` and `.banner` display modes, setting `displayMode: .alert` works fine.

**To Reproduce**
1. Submit login form with invalid entries
2. toaster displays and remains until tapped
3. subsequent submissions display toaster and clear after the default duration

**Smartphone:**
 - Device: Xcode simulator iPhone 12 and actual iPhone 12 device
 - OS: iOS 15.2.1

**Code**

```
final class SessionManager: ObservableObject {
...
    @Published var toastShow = false
    @Published var toaster = AlertToast(type: .regular) {
        didSet{ toastShow.toggle() }
    }
...
    func signIn(email: String, password: String) {
        Amplify.Auth.signIn(username: email, password: password)
            .resultPublisher
            .sink {
                if case let .failure(authError) = $0 {
                    DispatchQueue.main.async {
                        self.toaster = AlertToast(
                            displayMode: .hud,
                            type: .error(.red),
                            title: "Login Error",
                            subTitle: authError.errorDescription
                        )
                    }
                }
            }
            ....
}

@main
struct Auth2App: App {
  @StateObject var sessionManager = SessionManager.shared

    var body: some Scene {
        
        WindowGroup {
            switch sessionManager.authState {
            case .signIn:
                LoginView()
                    .environmentObject(sessionManager)
                    .toast(isPresenting: $sessionManager.toastShow){
                        sessionManager.toaster
                    }
...
}
```

**Comment by aledebla03** [comment]
Same issue here

**Comment by neoighodaro** [comment]
Hey, any workarounds? Seems this is not getting fixed

**Comment by kawaja** [comment]
I have been looking at this and believe I have a fix. I'll raise a PR with my modifications.

The issue relates to changing from one `displayMode` to another. It actually occurs not just on the first call, but any time a new `AlertToast` is created with a different `displayMode`. Since the initialiser defaults to `.alert`, and first call is actually the second call (the first being the initialisation), the task to take the toast down is never created.

So, the workaround (without my changes) is to create the first `AlertToast` with the `displayMode` you intend to use throughout the rest of the app:

In your example @pulpfree, change this:
```
    @Published var toaster = AlertToast(type: .regular) {
```

to this:
```
    @Published var toaster = AlertToast(displayMode: .hud, type: .regular) {
```

The workaround does not work if you want to use more than one `displayMode` in the same app.

**Comment by elai950** [comment]
Hey @pulpfree ,
I tried to reproduce this bug but with no success.
I guess that `DispatchQueue` you've put in the sink operator has to do something that causes this kind of problem.
It's always better in Combine to use the `.recieve(on:)` operator and not create a new thread inside the sink.
Also, check your custom operator to check for any problems there (`resultPublisher`).

If you strip down your ObservableObject and keep only the Published variable you will see that it works as it should.

**Comment by pulpfree** [comment]
Hey @elai950. Thanks for the info, appreciate it.
