### ISSUE TITLE
Loading Toast Cannot Be Dismissed

### ISSUE THREAD

**Issue by RudraSen2** [elai950/AlertToast#47]
**Describe the bug**
The Loading Toast, cannot be dismissed by Clicking on The Toast but can be dismissed using the button from which the toast is popped up. All Other Toasts can be dismissed by clicking on the toast.

**To Reproduce**
1. Implement Loading Toast
2. Run The App and Start off the toast.
3. Click on the spinner and it would not dismiss.

**Expected behavior**
I want to dismiss the loading toast by clicking on the spinner like in other toasts.

**Screenshots**
Sorry, No Screenshots are available at this point of time. You can ask for them later.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.3.1
 - Browser: Safari
 - Version: Latest

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Mini (Simulator)
 - OS: iOS 15 Latest
 - Browser: Safari
 - Version: Latest

**Additional context**
N/A

**Comment by elai950** [comment]
Hey @RudraSen2 ,
A tap to dismiss on a loader would not be a very useful feature because the user should not be able to dismiss the loading alert in case there is some processing logic.
This is why I decided that the loading alert would not be possible to dismiss.

If you really need this feature, you can always fork the library and change the code inside.
