### ISSUE TITLE
No such module AlertToast

### ISSUE THREAD

**Issue by goxyed** [elai950/AlertToast#6]
I try to install manually AlertToast as per instructions, but I got error "No such module AlertToast" in Xcode 12.4.
Is there way to fix this?

**Comment by elai950** [comment]
If I understand you right, after import the file, there's no need to add on each file `import AlertToast`.
Is that the case?
If not, please provide more information and a screen shot with your error.

**Comment by elai950** [comment]
Closed for inactivity.

**Comment by jonsaw** [comment]
I'm getting the same error:

<img width="560" alt="Screenshot 2021-11-25 at 6 32 07 PM" src="https://user-images.githubusercontent.com/1572333/143425557-06455b96-6659-49cd-9071-dfdc0acfec81.png">

`AlertToast` is in the list of dependencies:

<img width="256" alt="Screenshot 2021-11-25 at 6 32 45 PM" src="https://user-images.githubusercontent.com/1572333/143425492-a13397f5-beda-4203-9d2c-aaf262e9e17d.png">

I added `AlertToast` using Swift Package Manager

 > File > Add Packages

**Comment by nhershy** [comment]
I was getting the same error. The problem was that even though I added the AlertToast Packaged Dependency correctly, it did not automatically add it or recognize it in my Project libraries. 

In the Project Navigator, I clicked on my top level Project, then clicked on my project again in Targets, then I added the AlertToast to my Frameworks, Libraries, and Embedded Content

![Image](https://github.com/user-attachments/assets/eac48fb9-f879-4537-8230-742307b0a377)
