### ISSUE TITLE
Hud toast appears behind the navigation toolbar

### ISSUE THREAD

**Issue by 27shutterclicks** [elai950/AlertToast#96]
**Describe the bug**
When presenting a toast with a system image icon and using the .hud display mode, the toast appears behind the navigation toolbar.

![image](https://github.com/user-attachments/assets/50b22654-6771-4191-b97d-63d834efd1ab)

This also causes for the toast to not be clickable unless you manage to find a small area peaking from under the toolbar that covers it.

The toast was added to a view that gets loaded in another template view. However, the same thing happens without the template, by adding the toast to the root VStack of the view:

![image](https://github.com/user-attachments/assets/dfef3013-5ca9-42c0-8c2e-6ae7e6dd25b5)

**To Reproduce**
I just added a toast as per the documentation.

**Expected behavior**
The toast should appear above everything else, including the navigation toolbar.

**Comment by donniefitz2** [comment]
I'm experiencing this issue too. Really like this hud message because it allows more text. Anyone know of a work-around?

**Comment by elai950** [comment]
This is a known bug.
The problem is that NavigationView is always at the very top in the views hierarchy.
As far as I know, there's no option to change that due to Apple limitations.
I think it's because overlapping a view on him would result in poor UX for the user.

Maybe with the latest SwiftUI there's a work around but I'm not familiar with that.

You're more than welcome to share your thoughts and ideas and maybe we can solve this together.
Meanwhile there's the `offset` parameter which is not ideal.
